In [3]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split
from scipy import stats
import env
import acquire
import prepare
import os

# turn off pink boxes for demo
import warnings
warnings.filterwarnings("ignore")

In [4]:
train, validate, test = prepare.prep_telco_data(acquire.get_telco_data())

In [5]:
train.head()

,senior_citizen,tenure,multiple_lines,monthly_charges,total_charges,contract_type,internet_service_type,payment_type,is_male,has_partner,...,month_to_month_contract,one_year_contract,two_year_contract,dsl_internet,fiber_optic_internet,no_internet_service,bank_transfer_payment_automatic,credit_card_payment_automatic,electronic_check_payment,mailed_check_payment
1196,0,63,Yes,68.80,4111.35,One year,DSL,Bank transfer (automatic),1,0,...,0,1,0,1,0,0,1,0,0,0
4239,1,23,No,75.40,1643.55,Month-to-month,Fiber optic,Bank transfer (automatic),0,0,...,1,0,0,0,1,0,1,0,0,0
846,0,42,No phone service,45.10,2049.05,One year,DSL,Credit card (automatic),1,1,...,0,1,0,1,0,0,0,1,0,0
6014,0,60,No,20.55,1205.05,Two year,None,Mailed check,1,1,...,0,0,1,0,0,1,0,0,0,1
6667,0,1,Yes,25.75,25.75,Month-to-month,None,Mailed check,0,0,...,1,0,0,0,0,1,0,0,0,1

In [6]:
print(train.shape)
print(validate.shape)
print(test.shape)

(3937, 32)
(1688, 32)
(1407, 32)